"""Backward-compatible re-export shim.

New code should import directly from:
  - backend.models.screenshot  (Pydantic schemas, dataclasses, ScreenshotType)
  - backend.services.screenshot (analysis functions)
"""

from backend.services.screenshot import (
    CLASSIFY_PROMPT,
    EXTRACT_ACTIVITY_PROMPT,
    EXTRACT_GENERIC_PROMPT,
    EXTRACT_TRAINING_LOAD_CHART_PROMPT,
    EXTRACT_WELLNESS_MULTI_PROMPT,
    EXTRACT_WELLNESS_SINGLE_PROMPT,
    MIN_SCREENSHOT_CLASSIFICATION_CONFIDENCE,
    ActivityExtraction,
    AsyncOpenAI,
    ChartDateRange,
    ConfidenceEntry,
    ExtractionResult,
    GenericExtraction,
    GenericObservation,
    OpenAIError,
    ScreenshotClassification,
    ScreenshotClassificationModel,
    ScreenshotType,
    TrainingLoadChartExtraction,
    TrainingLoadPoint,
    WellnessDayEntry,
    WellnessMultiExtraction,
    WellnessSingleExtraction,
    _call_vision,
    analyze_screenshot,
    classify_screenshot,
    extract_from_screenshot,
    logger,
    settings,
)

__all__ = [
    "CLASSIFY_PROMPT",
    "EXTRACT_ACTIVITY_PROMPT",
    "EXTRACT_GENERIC_PROMPT",
    "EXTRACT_TRAINING_LOAD_CHART_PROMPT",
    "EXTRACT_WELLNESS_MULTI_PROMPT",
    "EXTRACT_WELLNESS_SINGLE_PROMPT",
    "MIN_SCREENSHOT_CLASSIFICATION_CONFIDENCE",
    "ActivityExtraction",
    "AsyncOpenAI",
    "ChartDateRange",
    "ConfidenceEntry",
    "ExtractionResult",
    "GenericExtraction",
    "GenericObservation",
    "OpenAIError",
    "ScreenshotClassification",
    "ScreenshotClassificationModel",
    "ScreenshotType",
    "TrainingLoadChartExtraction",
    "TrainingLoadPoint",
    "WellnessDayEntry",
    "WellnessMultiExtraction",
    "WellnessSingleExtraction",
    "_call_vision",
    "analyze_screenshot",
    "classify_screenshot",
    "extract_from_screenshot",
    "logger",
    "settings",
]
