repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: uv run ruff check .
        entry: uv run ruff check .
        language: system
        pass_filenames: false
      - id: ruff-format-check
        name: uv run ruff format --check .
        entry: uv run ruff format --check .
        language: system
        pass_filenames: false
      - id: ty-check
        name: uv run ty check
        entry: uv run ty check
        language: system
        pass_filenames: false
        stages: [pre-push]
